---
- name: Update yum packages on Linux
  hosts: all
  gather_facts: yes

  tasks:

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      become: yes
      when: tags.demo == "cicd"

    - name: install packages
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - wget
        - tar
        - python3-pip
        - nginx
        - postgresql
      become: yes
      when: tags.demo == "cicd"
